version: '3'

services:
  db:
    container_name: weather-twitter-db 
    image: postgres:13
    environment: 
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "3001:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  app:
    container_name: weather-twitter-api
    build: .
    volumes:
      - .:/app
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - OPEN_WEATHER_API_KEY=02afd06cd333421bd19a8381a28a5d26
    ports:
      - "3000:3000"
    depends_on:
      - db
